name: Lint
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install Node.js dependencies (npm ci)
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Run Prettier Check
        run: npm run prettier:check
